disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Templates

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
line_length:
    warning: 150
    error: 250
    ignores_comments: true
    ignores_urls: true
    ignores_interpolated_strings: true

identifier_name:
  excluded: # excluded via string array
    - id

type_name:
  excluded: # excluded via string array
    - ID
